import { cx } from 'classix';
import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div className='px-8'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex min-h-screen flex-1 flex-col items-center justify-center py-16'>
        <h1 className='m-0 text-center text-6xl leading-tight'>
          Welcome to{' '}
          <a className={'text-blue-600 no-underline [&:is(:hover,:focus,:active)]:underline'} href='https://nextjs.org'>
            Next.js!
          </a>
        </h1>

        <p className='my-16 text-center text-2xl leading-normal'>
          Get started by editing{' '}
          <code className='rounded-[5px] bg-[#fafafa] p-3 font-mono text-[1.1rem] dark:bg-[#111]'>pages/index.tsx</code>
        </p>

        <div className='flex w-full max-w-[800px] flex-col flex-wrap items-center justify-center sm:w-auto sm:flex-row'>
          <Card
            heading='Documentation &rarr;'
            description='Find in-depth information about Next.js features and API.'
            url='https://nextjs.org/docs'
          />

          <Card
            heading='Learn &rarr;'
            description='Learn about Next.js in an interactive course with quizzes!'
            url='https://nextjs.org/learn'
          />

          <Card
            heading='Examples &rarr;'
            description='Discover and deploy boilerplate example Next.js projects.'
            url='https://github.com/vercel/next.js/tree/canary/examples'
          />

          <Card
            heading='Deploy &rarr;'
            description='Instantly deploy your Next.js site to a public URL with Vercel.'
            url='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          />
        </div>
      </main>

      <footer className='flex flex-1 border-t border-solid border-[#eaeaea] py-8 dark:border-[#222]'>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
          className='flex grow items-center justify-center'
        >
          Powered by{' '}
          <span className='ml-2 h-4'>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} className='dark:invert' />
          </span>
        </a>
      </footer>
    </div>
  );
}

function Card({ heading, description, url }: { heading: string; description: string; url: string }) {
  return (
    <a
      href={url}
      className={cx(
        '[&:is(:hover,:focus,:active)]:border-blue-600 [&:is(:hover,:focus,:active)]:text-blue-600',
        'transition-colors ease-[cubic-bezier(0.25,0.1,0.25,1.0)]',
        'rounded-[10px] border border-solid dark:border-[#222]',
        'text-left text-inherit no-underline',
        'm-4 max-w-[300px] p-6',
      )}
    >
      <h2 className='mb-4 text-2xl leading-[inherit]'>{heading}</h2>
      <p className='m-0 text-xl leading-[inherit]'>{description}</p>
    </a>
  );
}
